from django.urls import path

from dashboard.views import (
    AdminAuditLogView,
    AdminAuditTablePartialView,
    AdminClinicSaveView,
    AdminClinicsTablePartialView,
    AdminClinicsView,
    AdminLoginTablePartialView,
    AdminStaffSaveView,
    AdminStaffTablePartialView,
    AdminStaffView,
    DashboardHomeView,
    DoctorBulkDischargeView,
    DoctorBulkReadmitView,
    DoctorDischargePanelPartialView,
    DoctorDischargedPatientDetailView,
    DoctorDischargedPatientSummaryDownloadView,
    DoctorDischargedPatientSummaryPrintView,
    DoctorDischargedPartialView,
    DoctorQueueConsultationAIView,
    DoctorQueueConsultationFormView,
    DoctorQueueConsultationSubmitView,
    NurseAwaitingPartialView,
    NursePatientSelectPartialView,
    NursePatientRegisterView,
    NurseTriageFormPartialView,
    NurseTriageSubmitView,
    QueuePartialView,
    ReceptionistPatientsPartialView,
    TriageSeverityDocsView,
    UnauthorizedView,
)

app_name = "dashboard"

urlpatterns = [
    path("", DashboardHomeView.as_view(), name="home"),
    path("unauthorized/", UnauthorizedView.as_view(), name="unauthorized"),
    path("queue/partial/", QueuePartialView.as_view(), name="queue-partial"),
    path("nurse/awaiting/partial/", NurseAwaitingPartialView.as_view(), name="nurse-awaiting-partial"),
    path(
        "nurse/patient-select/partial/",
        NursePatientSelectPartialView.as_view(),
        name="nurse-patient-select-partial",
    ),
    path("receptionist/patients/partial/", ReceptionistPatientsPartialView.as_view(), name="receptionist-patients-partial"),
    path("doctor/discharged/partial/", DoctorDischargedPartialView.as_view(), name="doctor-discharged-partial"),
    path("doctor/discharge-panel/partial/", DoctorDischargePanelPartialView.as_view(), name="doctor-discharge-panel-partial"),
    path(
        "doctor/discharged/<uuid:pk>/",
        DoctorDischargedPatientDetailView.as_view(),
        name="doctor-discharged-detail",
    ),
    path(
        "doctor/discharged/<uuid:pk>/summary.pdf",
        DoctorDischargedPatientSummaryDownloadView.as_view(),
        name="doctor-discharged-summary-download",
    ),
    path(
        "doctor/discharged/<uuid:pk>/print/",
        DoctorDischargedPatientSummaryPrintView.as_view(),
        name="doctor-discharged-summary-print",
    ),
    path(
        "doctor/queue/consultation/form/",
        DoctorQueueConsultationFormView.as_view(),
        name="doctor-queue-consultation-form",
    ),
    path(
        "doctor/queue/consultation/submit/",
        DoctorQueueConsultationSubmitView.as_view(),
        name="doctor-queue-consultation-submit",
    ),
    path(
        "doctor/queue/consultation/ai/",
        DoctorQueueConsultationAIView.as_view(),
        name="doctor-queue-consultation-ai",
    ),
    path("nurse/patient/register/", NursePatientRegisterView.as_view(), name="nurse-patient-register"),
    path("nurse/triage/form/", NurseTriageFormPartialView.as_view(), name="nurse-triage-form"),
    path("nurse/triage/submit/", NurseTriageSubmitView.as_view(), name="nurse-triage-submit"),
    path("docs/triage-severity/", TriageSeverityDocsView.as_view(), name="triage-severity-docs"),
    path("bulk-discharge/", DoctorBulkDischargeView.as_view(), name="bulk-discharge"),
    path("bulk-readmit/", DoctorBulkReadmitView.as_view(), name="bulk-readmit"),
    path("audit-logs/", AdminAuditLogView.as_view(), name="admin-audit"),
    path("audit-logs/audit/partial/", AdminAuditTablePartialView.as_view(), name="admin-audit-partial"),
    path("audit-logs/login/partial/", AdminLoginTablePartialView.as_view(), name="admin-login-partial"),
    path("manage/clinics/", AdminClinicsView.as_view(), name="admin-clinics"),
    path("manage/clinics/list/partial/", AdminClinicsTablePartialView.as_view(), name="admin-clinics-partial"),
    path("manage/clinics/save/", AdminClinicSaveView.as_view(), name="admin-clinic-save"),
    path("manage/staff/", AdminStaffView.as_view(), name="admin-staff"),
    path("manage/staff/list/partial/", AdminStaffTablePartialView.as_view(), name="admin-staff-partial"),
    path("manage/staff/save/", AdminStaffSaveView.as_view(), name="admin-staff-save"),
]
