# Generated by Django 5.1.15 on 2026-05-28 00:54

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LoginAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("email_attempted", models.EmailField(db_index=True, max_length=254)),
                ("ip_address", models.GenericIPAddressField()),
                ("success", models.BooleanField(default=False)),
                ("user_agent", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["email_attempted", "success", "timestamp"],
                        name="auditlogs_l_email_a_0296f8_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("archive", "Archive"),
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("login_failed", "Login Failed"),
                            ("bulk_discharge", "Bulk Discharge"),
                            ("admit", "Admit"),
                            ("discharge", "Discharge"),
                            ("unauthorized_access", "Unauthorized Access"),
                            ("api_access", "API Access"),
                            ("security_violation", "Security Violation"),
                        ],
                        db_index=True,
                        max_length=64,
                    ),
                ),
                ("object_type", models.CharField(db_index=True, max_length=128)),
                ("object_id", models.CharField(blank=True, max_length=64)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["action", "timestamp"], name="auditlogs_a_action_caf260_idx"
                    ),
                    models.Index(
                        fields=["object_type", "object_id"], name="auditlogs_a_object__f248cb_idx"
                    ),
                ],
            },
        ),
    ]
