# Generated by Django 5.1.15 on 2026-05-28 00:54

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import common.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("patients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TriageRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "blood_pressure",
                    models.CharField(
                        max_length=16, validators=[common.validators.validate_blood_pressure]
                    ),
                ),
                (
                    "heart_rate",
                    models.PositiveSmallIntegerField(
                        validators=[common.validators.validate_heart_rate]
                    ),
                ),
                (
                    "respiratory_rate",
                    models.PositiveSmallIntegerField(
                        validators=[common.validators.validate_respiratory_rate]
                    ),
                ),
                (
                    "oxygen_saturation",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[common.validators.validate_oxygen_saturation],
                    ),
                ),
                (
                    "body_temperature",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=4,
                        validators=[common.validators.validate_body_temperature],
                    ),
                ),
                ("symptoms", models.TextField()),
                (
                    "severity_level",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("moderate", "Moderate"),
                            ("stable", "Stable"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                ("priority_score", models.PositiveSmallIntegerField(db_index=True, default=0)),
                (
                    "triage_status",
                    models.CharField(
                        choices=[
                            ("waiting", "Waiting"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("escalated", "Escalated"),
                        ],
                        db_index=True,
                        default="waiting",
                        max_length=16,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "nurse",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="triage_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="triage_records",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "ordering": ["-priority_score", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["patient", "is_active"], name="triage_tria_patient_750c85_idx"
                    ),
                    models.Index(
                        fields=["severity_level", "triage_status"],
                        name="triage_tria_severit_ce507d_idx",
                    ),
                ],
            },
        ),
    ]
