# Generated by Django 5.1.15 on 2026-05-29 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0002_triage_clinical_assessment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='triagerecord',
            name='critical_findings',
        ),
        migrations.RemoveField(
            model_name='triagerecord',
            name='possible_conditions',
        ),
        migrations.RemoveField(
            model_name='triagerecord',
            name='recommended_action',
        ),
        migrations.RemoveField(
            model_name='triagerecord',
            name='requires_immediate_attention',
        ),
        migrations.RemoveField(
            model_name='triagerecord',
            name='triage_reasoning',
        ),
        migrations.RemoveField(
            model_name='triagerecord',
            name='triage_tier',
        ),
    ]
