# Generated by Django 5.1.15 on 2026-05-28 00:54

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("patients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Consultation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("diagnosis", models.TextField()),
                ("treatment", models.TextField()),
                ("prescription", models.TextField(blank=True)),
                ("admitted", models.BooleanField(db_index=True, default=False)),
                ("discharged", models.BooleanField(db_index=True, default=False)),
                ("consultation_notes", models.TextField(blank=True)),
                ("admitted_at", models.DateTimeField(blank=True, null=True)),
                ("discharged_at", models.DateTimeField(blank=True, null=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        limit_choices_to={"role": "doctor"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="consultations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consultations",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["patient", "admitted", "discharged"],
                        name="consultatio_patient_5696ac_idx",
                    ),
                    models.Index(
                        fields=["doctor", "discharged"], name="consultatio_doctor__c46d8c_idx"
                    ),
                ],
            },
        ),
    ]
